### PR TITLE
dont save file in insert mode

### PR DESCRIPTION
**Pull request by skv-headless**
if g:auto_save_in_insert_mode = 0

When I'm typing I don't expect file to save until I quit insert mode.

### CODE REVIEW

**Comment by 907th** [comment]
@skv-headless Hello! Why do we need this check? When `g:auto_save_in_insert_mode = 0` it is only `InsertLeave` and `CursorHold` events used and they don't work in `insert` mode (as far as I know).

**Comment by skv-headless** [comment]
vim version 7.4.889
janus
let g:auto_save_in_insert_mode = 0

bug1 mov

**Comment by 907th** [comment]
`let g:auto_save_in_insert_mode = 0` works only when placed in `.vimrc`. It can not be enabled/disabled from command mode after Vim started. Did you tried to set the option to `0` in command mode?

**Comment by skv-headless** [comment]
I found a problem. I put ```let g:auto_save_in_insert_mode = 0``` in .vimrc.before previously it was in .vimrc.after. Now it is working.

**Comment by 907th** [comment]
@skv-headless In other words, `g:auto_save_in_insert_mode` must be set before `vim-auto-save` plugin loaded. Setting it later will not change anything. Yes, I would prefer it to work from command mode too. To do so also we need to refactor [this](https://github.com/skv-headless/vim-auto-save/blob/imrove-insert/plugin/AutoSave.vim#L46). I shall think about it and your proposal in next few days. Thank you for contributing! Keep it open for now

**Comment by leoroos** [comment]
Seems obsolete after the addressed option has now been removed

**Pull request closed without merging**
