### PR TITLE
Add pre-save hook to be able to abort auto save if needed

### PR DESCRIPTION
**Pull request by zigius**

### CODE REVIEW

**Comment by 907th** [comment]
Great! Thank you!

**Comment by 907th** [comment]
@zigius I'm going to make a little refactoring of the code, so the interface may change. I will let you know when I'm done.

**Comment by 907th** [comment]
@zigius I changed controlling variable name to `g:auto_save_abort`. Set it to 1 to abort the save. See the docs for example.

**Comment by zigius** [comment]
Thanks! i updated my hook

**Pull request merged**
